sources:
  - name: raw_source # this is the source_name
    database: test
    schema: raw
    tables:
      - name: tbl_mara_curated_scd1
      - name: tbl_vbap_curated_scd1
      - name: tbl_vbak_curated_scd1
      - name: tbl_lfa1_curated_scd1
      - name: tbl_vbep_curated_scd1
      - name: tbl_ekpo_curated_scd1
      - name: tbl_ekko_curated_scd1
      - name: tbl_kna1_curated_scd1
      - name: knvv
      - name: marc
      - name: march
      - name: mbew
      - name: mbewh
      - name: mchb
      - name: mchbh
      - name: mkol
      - name: mkolh
      - name: mska
      - name: mskah
      - name: mslb
      - name: mslbh
      - name: mvke
      - name: mch1
      - name: mkpf
      - name: mseg
      - name: t001l
      - name: t001w
      - name: vbak
      - name: vbap
      - name: otm_shipment
      - name: otm_contact
      - name: otm_order
      - name: tbl_lips_curated_scd1
      - name: tbl_likp_curated_scd1 
      - name: tbl_vbuk_curated_scd1